# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd8c74b5a5c6c9418c453e85b794724f9157521a8de72b9651f825352faa27c32a4a697cd151111cf32ae45ad46ecf7af0ecea7499955c52648623fa5dda0dfd

test:
  secret_key_base: 09a17238cea86d6774084fac0235b21139ce4f21b2e62ab9eef256f083912323d255229668e41ab0fbb32745100eee7de9ce9855bae24175c2c4e419016c95a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
